import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import AppProvider from "@/components/layout/AppProvider";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/contextProvider/CartContext";

const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
          <CartProvider>
          <Toaster />
          <Header />
          {/* <RouteLoader /> */}
          
            {children}
          </CartProvider>
          <footer className="mt-12 text-center text-gray-500">
            <hr className="mb-6" />
            &copy; 2024 All rights reserved
          </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
